config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :papers do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :authors do
    collection do
      delete 'destroy_multiple'
    end
  end

  # It's important these files are served from within the 'cda' folder, else
  # the global RePEc service will complain.
  get 'repec/cda/cdaarch.redif', to: 'browser#cdaarch'
  get 'repec/cda/cdaseri.redif', to: 'browser#cdaseri'

  get 'repec/cda/wpaper/:id.redif', as: :paper_redif, action: :show_redif, controller: :browser
  get '/:path', to: 'browser#index', as: :pathway, constraints: { path: /repec[\/a-zA-Z]*/i }

  # Some helpful redirects
  get '/login', to: redirect('/papers')
  get '/admin', to: redirect('/papers')

  # FileController to avoid ActiveStorage redirects (credit: https://github.com/rails/rails/issues/31419#issuecomment-399118697)
  get '/files/:key/*filename', to: 'files#show', as: :rails_public_blob
  direct :public_blob do |blob, options|
    route_for(:rails_public_blob, blob.key, blob.filename, options)
  end
  resource :files, only: :show

  root to: 'browser#index'
end

app/controllers/browser_controller.rb
class BrowserController < ApplicationController
  skip_before_action :authenticate, only: [:index, :show_redif, :cdaarch, :cdaseri]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.includes(:authors).order(:id).all

    @path = params[:path]

    headers['Content-Type'] = 'text/html; charset=utf-8'

    valid_paths = [
      nil,
      'repec',
      'repec/cda',
      'repec/cda/wpaper'
    ]

    unless valid_paths.include?(@path)
      Rails.logger.debug "Raising 404 due to invalid path request: '#{@path}'"
      raise ActionController::RoutingError.new('Not Found')
    end

    begin
      render 'browser/index', layout: 'browser'
    rescue ActionView::MissingTemplate => e
      Rails.logger.debug "Raising 404 due to invalid format request: '#{e}'"
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  # Emulate static file cdaarch.redif
  def cdaarch
    render 'cdaarch.redif', layout: false
  end

  # Emulate static file cdaseri.redif
  def cdaseri
    render 'cdaseri.redif', layout: false
  end

  def show_redif
    @paper = Paper.find(params[:id])

    # RePEc protocol requires we serve files as UTF-8 with file extension .redif
    headers['Content-Type'] = 'text/plain; charset=utf-8'

    render action: 'show', formats: :redif
  end
end

app/helpers/browser_helper.rb
module BrowserHelper
  # file_size = nil implies entry is a directory
  def dir_entry(timestamp, body, url, file_size = nil)
    str = Time.at(timestamp).strftime("%-m/%-d/%Y").rjust(10) + " " + Time.at(timestamp).strftime("%l:%M %p")
    if file_size.nil?
      return (str + "&lt;dir&gt;".rjust(19) + " " + link_to(body, url)).html_safe
    else
      return (str + file_size.to_s.rjust(13) + " " + link_to(body, url)).html_safe
    end
  end
end

app/views/browser/index.html.erb
<pre>
<% if @path == "repec" %>
<%= link_to '[To Parent Directory]', "/" %><br>
<%= dir_entry(Time.now, 'cda', '/repec/cda') %>
<% elsif @path == "repec/cda" %>
<%= link_to '[To Parent Directory]', "/repec" %><br>
<%= dir_entry(File.mtime(Rails.root.join('app', 'views', 'browser', 'cdaarch.redif')), 'cdaarch.redif', '/repec/cda/cdaarch.redif', File.size(Rails.root.join('app', 'views', 'browser', 'cdaarch.redif'))) %>
<%= dir_entry(File.mtime(Rails.root.join('app', 'views', 'browser', 'cdaseri.redif')), 'cdaseri.redif', '/repec/cda/cdaseri.redif', File.size(Rails.root.join('app', 'views', 'browser', 'cdaseri.redif'))) %>
<%= dir_entry(Time.now, 'wpaper', "/repec/cda/wpaper") %><br>
<% elsif @path == "repec/cda/wpaper" %>
<%= link_to '[To Parent Directory]', "/repec/cda" %><br>
<% @papers.each do |paper| %>
<% cache paper do %><%= dir_entry(paper.created_at.in_time_zone('Pacific Time (US & Canada)'), "#{paper.id}.redif", paper_redif_path(paper), PapersController.render('browser/show.redif', assigns: { paper: paper }).length ) %><% end %>
<% end %>
<% else %>
<%= dir_entry(Time.now, 'repec', '/repec') %>
<% end %>
</pre>

app/views/browser/show.rdf.erb
Template-Type: ReDIF-Paper 1.0
<% @paper.authors.each do |author| %>
Author-Name: <%= author.name %>
<% if author.name.split.count > 2 %>
Author-Name-First: <%= author.name.split[0..-2].join(' ') %>
Author-Name-Last: <%= author.name.split[-1] %>
<% else %>
Author-Name-First: <%= author.name.split[0] %>
Author-Name-Last: <%= author.name.split[-1] %>
<% end %>
<% end %>Author-Workplace-Name: Department of Economics, University of California Davis
Title: <%= @paper.title.strip %>
Abstract: <%= @paper.abstract.strip %>
Length: <%= @paper.paper_length %>
File-URL: <%= polymorphic_url(@paper.file) %>
File-Format: Application/pdf
Number: <%= @paper.paper_number %>
Classification-JEL: <%= @paper.classification_jel.strip %>
KeyWords: <%= @paper.keywords.strip %>
Creation-Date: <%= @paper.created_at.in_time_zone('Pacific Time (US & Canada)').strftime('%Y%m%d') %>
<% if @paper.paper_number < 100 %>
Handle: RePEc:cda:wpaper:00-<%= @paper.paper_number %>
<% elsif @paper.paper_number < 1000 %>
Handle: RePEc:cda:wpaper:0<%= @paper.paper_number.to_s[0] %>-<%= @paper.paper_number.to_s[1..2] %>
<% elsif @paper.paper_number < 10000 %>
Handle: RePEc:cda:wpaper:<%= @paper.paper_number.to_s[0..1] %>-<%= @paper.paper_number.to_s[2..3] %>
<% end %>

app/views/browser/show.redif.erb
Template-Type: ReDIF-Paper 1.0
<% @paper.authors.each do |author| %>
Author-Name: <%= author.name %>
<% if author.name.split.count > 2 %>
Author-Name-First: <%= author.name.split[0..-2].join(' ') %>
Author-Name-Last: <%= author.name.split[-1] %>
<% else %>
Author-Name-First: <%= author.name.split[0] %>
Author-Name-Last: <%= author.name.split[-1] %>
<% end %>
<% end %>Author-Workplace-Name: Department of Economics, University of California Davis
Title: <%= @paper.title.strip %>
Abstract: <%= @paper.abstract.strip.gsub("\r", '').gsub("\n", "\n ") %>
Length: <%= @paper.paper_length %>
File-URL: <%= public_blob_url(@paper.file) %>
File-Format: application/pdf
Number: <%= @paper.id %>
Classification-JEL: <%= @paper.prettify_jel_codes %>
KeyWords: <%= @paper.keywords.strip %>
Creation-Date: <%= @paper.created_at.in_time_zone('Pacific Time (US & Canada)').strftime('%Y%m%d') %>
Handle: RePEc:cda:wpaper:<%= @paper.id %>