config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :papers do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :authors do
    collection do
      delete 'destroy_multiple'
    end
  end

  # It's important these files are served from within the 'cda' folder, else
  # the global RePEc service will complain.
  get 'repec/cda/cdaarch.redif', to: 'browser#cdaarch'
  get 'repec/cda/cdaseri.redif', to: 'browser#cdaseri'

  get 'repec/cda/wpaper/:id.redif', as: :paper_redif, action: :show_redif, controller: :browser
  get '/:path', to: 'browser#index', as: :pathway, constraints: { path: /repec[\/a-zA-Z]*/i }

  # Some helpful redirects
  get '/login', to: redirect('/papers')
  get '/admin', to: redirect('/papers')

  # FileController to avoid ActiveStorage redirects (credit: https://github.com/rails/rails/issues/31419#issuecomment-399118697)
  get '/files/:key/*filename', to: 'files#show', as: :rails_public_blob
  direct :public_blob do |blob, options|
    route_for(:rails_public_blob, blob.key, blob.filename, options)
  end
  resource :files, only: :show

  root to: 'browser#index'
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :authors_papers
  has_many :papers, through: :authors_papers

  validates :name, :presence => true

  def self.search(search = nil)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  add_breadcrumb "Authors", :authors_path

  def new
    @author = Author.new
    add_breadcrumb "Create author", new_author_path
  end

  def index
    @authors = Author.search(params[:search]).order(:name).page(params[:page]).per(30)
  end

  def show
    @author = Author.find(params[:id])
    add_breadcrumb "Show author", @author
  end

  def edit
    @author = Author.find(params[:id])
    add_breadcrumb "Edit author", edit_author_path
  end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html {
          flash[:success] = "Author was successfully created."
          redirect_to @author
        }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html {
          flash[:success] = "Author was successfully updated."
          redirect_to @author
        }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @author.destroy
    respond_to do |format|
      format.html {
        flash[:success] = "Author was successfully destroyed."
        redirect_to authors_url
      }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    Author.destroy(params[:authors])

    respond_to do |format|
      format.html { redirect_to authors_path }
      format.json { head :no_content }
    end
  end

private
  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<div class="container">
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h4>
      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="create form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder:"Name" %>
  </div>

  <div class="actions" id="submit_button">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>
</div>

app/views/authors/edit.html.erb
<%= stylesheet_link_tag 'authors', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
  <%= render 'form', author: @author %>
</div>

app/views/authors/index.html.erb
<%= stylesheet_link_tag 'authors', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
<%= form_tag authors_path, { :method => 'get', class: "container", role: "search" }  do %>
  <div class="main">
    <div class="input-group">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for authors" %>
      <div class="input-group-append">
        <button class="btn btn-dark" type="button">
          <i class="fa fa-search"></i>
        </button>
      </div>
    </div>
  </div>
<% end %>

<div id="actions">
  <div class="float-left">
    <button type="button" id="check_all" onclick="toggleButton()" class="btn btn-outline-secondary">Select all</button>
  </div>
  <div class="float-right">
    <%= link_to new_author_path, class: "btn btn-outline-secondary" do %>
      <i class="fas fa-user-plus"></i>Create Author
    <% end %>
  </div>
</div>

<%= form_tag destroy_multiple_authors_path, method: :delete do %>
  <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Are you sure?</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">Would you like to remove these authors from the list?</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
          <%= button_tag type: 'submit', method: :delete, class: "btn btn-danger" do %>
            <i class="fas fa-trash-alt"></i>Delete
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal", id="delete_all_btn">
    <i class="fas fa-trash-alt"></i> Delete all
  </button>

  <div id="table" class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
        <th></th>
        <th scope="col">Authors</th>
        <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @authors.each do |author| %>
          <tr>
          <td align="center">
            <%= check_box_tag "authors[]", author.id %>
          </td>
          <td scope="row"><%= author.name %></td>
          <td>
            <div class="btn-group float-right">
              <%= link_to author, class: "btn btn-outline-secondary btn-sm" do %>
                <i class="fas fa-search"></i> Show
              <% end %>
              <%= link_to edit_author_path(author), class: "btn btn-outline-secondary btn-sm" do %>
                <i class="fas fa-user-edit"></i> Edit
              <% end %>
              <div class="modal" id="myModal<%= author.id %>">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title">Are you sure?</h4>
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">Would you like to remove this author from the list?</div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                      <%= link_to author, method: :delete, class: "btn btn-danger" do %>
                        <i class="fas fa-trash-alt"></i> Delete
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal<%= author.id %>">
                <i class="fas fa-trash-alt"></i> Delete
              </button>
            </div>
          </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="float-right" id="page_entries_info">
    <%= page_entries_info @authors %>
  </div>
<% end %>

  <div><%= paginate @authors, window: 2, entry_name: "authors" %></div>
</div>

app/views/authors/new.html.erb
<%= stylesheet_link_tag 'authors', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
  <%= render 'form', author: @author %>
</div>

app/views/authors/show.html.erb
<%= stylesheet_link_tag 'authors', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
  <table class="table table-bordered" id="show_table">
    <tr>
      <th>Author</th>
      <td><%= @author.name %></td>
    </tr>
    <tr>
      <th>Published at</th>
      <td><%= @author.created_at.in_time_zone('Pacific Time (US & Canada)').strftime('%B %e, %Y at %l:%M %p') %></td>
    </tr>
    <tr>
      <th>Updated at</th>
      <td><%= @author.updated_at.in_time_zone('Pacific Time (US & Canada)').strftime('%B %e, %Y at %l:%M %p') %></td>
    </tr>
  </table>

  <div class="float-right">
    <%= link_to edit_author_path(@author), class: "btn btn-outline-secondary" do %>
      <i class="fas fa-user-edit"></i> Edit
    <% end %>
    <%= link_to authors_path, class: "btn btn-outline-secondary" do %>
      Back <i class="fas fa-arrow-right"></i> 
    <% end %>
  </div>
</div>