config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :papers do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :authors do
    collection do
      delete 'destroy_multiple'
    end
  end

  # It's important these files are served from within the 'cda' folder, else
  # the global RePEc service will complain.
  get 'repec/cda/cdaarch.redif', to: 'browser#cdaarch'
  get 'repec/cda/cdaseri.redif', to: 'browser#cdaseri'

  get 'repec/cda/wpaper/:id.redif', as: :paper_redif, action: :show_redif, controller: :browser
  get '/:path', to: 'browser#index', as: :pathway, constraints: { path: /repec[\/a-zA-Z]*/i }

  # Some helpful redirects
  get '/login', to: redirect('/papers')
  get '/admin', to: redirect('/papers')

  # FileController to avoid ActiveStorage redirects (credit: https://github.com/rails/rails/issues/31419#issuecomment-399118697)
  get '/files/:key/*filename', to: 'files#show', as: :rails_public_blob
  direct :public_blob do |blob, options|
    route_for(:rails_public_blob, blob.key, blob.filename, options)
  end
  resource :files, only: :show

  root to: 'browser#index'
end

app/views/shared/_nav.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to papers_path, class: "navbar-brand" do %>
      <i class="fas fa-home"></i> RePEc
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to papers_path, class: "nav-link" do %>
            <i class="fas fa-file-alt"></i> Papers
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to authors_path, class: "nav-link" do %>
            <i class="fas fa-user"></i> Authors
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path, class: "nav-link" do %>
            <i class="fas fa-users"></i> Users
          <% end %>
        </li>
      </ul>
    </div>
  </nav>