config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :papers do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :authors do
    collection do
      delete 'destroy_multiple'
    end
  end

  # It's important these files are served from within the 'cda' folder, else
  # the global RePEc service will complain.
  get 'repec/cda/cdaarch.redif', to: 'browser#cdaarch'
  get 'repec/cda/cdaseri.redif', to: 'browser#cdaseri'

  get 'repec/cda/wpaper/:id.redif', as: :paper_redif, action: :show_redif, controller: :browser
  get '/:path', to: 'browser#index', as: :pathway, constraints: { path: /repec[\/a-zA-Z]*/i }

  # Some helpful redirects
  get '/login', to: redirect('/papers')
  get '/admin', to: redirect('/papers')

  # FileController to avoid ActiveStorage redirects (credit: https://github.com/rails/rails/issues/31419#issuecomment-399118697)
  get '/files/:key/*filename', to: 'files#show', as: :rails_public_blob
  direct :public_blob do |blob, options|
    route_for(:rails_public_blob, blob.key, blob.filename, options)
  end
  resource :files, only: :show

  root to: 'browser#index'
end

app/models/paper.rb
class Paper < ApplicationRecord
  has_many :authors_papers
  has_many :authors, -> { includes(:authors_papers).order('authors_papers.priority') }, through: :authors_papers

  has_one_attached :file

  validates :title, :abstract, :authors, presence: true
  validate :file_type

  # Returns the JEL codes prettified while removing invalid codes
  def prettify_jel_codes
    classification_jel.strip.gsub('.','').gsub(' ','').split(',').select{|e| /(^[A-Z][0-9]*$)/.match(e) != nil }.map{|e| e.strip}.join(', ')
  end

  private

  def file_type
    if file.attached? == false
      errors.add(:file, 'must have a document attached')
    elsif !file.content_type.in?(%w(application/pdf))
      errors.add(:file, 'must be a PDF')
    elsif file.byte_size > 500.megabytes
      errors.add(:file, 'size must be less than 500 MB')
    end
  end

  def self.search(search = nil)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]
  add_breadcrumb "Papers", :papers_path

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.search(params[:search]).order(created_at: :desc).page(params[:page]).per(30)
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    @paper = Paper.find(params[:id])
    add_breadcrumb "Show paper", @paper
  end

  # GET /papers/new
  def new
    @paper = Paper.new
    add_breadcrumb "Add paper", new_paper_path
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
    @priorities = {}
    @paper.authors_papers.each do |authors_paper|
      author_id = authors_paper.author_id
      @priorities[author_id] = authors_paper.priority
    end
    add_breadcrumb "Edit author", edit_paper_path
  end

  # POST /papers
  # POST /papers.json
  def create
    create_params = paper_params
    author_priorities = paper_params[:priorities].to_h.reject{ |k,v| v.empty? }
    create_params[:author_ids] = author_priorities.keys

    @paper = Paper.new(create_params.except(:priorities))
    @paper.paper_number = Paper.maximum('paper_number') + 1

    respond_to do |format|
      if @paper.save
        author_priorities.each do |id, priority|
          @paper.authors_papers.where(:author_id => id).update_all(priority: priority)
        end

        format.html {
          flash[:success] = "Paper was successfully created."
          redirect_to @paper
        }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    update_params = paper_params
    author_priorities = paper_params[:priorities].to_h.reject{ |k,v| v.empty? }
    update_params[:author_ids] = author_priorities.keys

    respond_to do |format|
      if @paper.update(update_params.except(:priorities))

          author_priorities.each do |id, priority|
            @paper.authors_papers.where(:author_id => id).update_all(priority: priority)
          end

        format.html {
          flash[:success] = "Paper was successfully updated."
          redirect_to @paper
        }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html {
        flash[:success] = "Paper was successfully destroyed."
        redirect_to papers_url
      }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    Paper.destroy(params[:papers])

    respond_to do |format|
      format.html { redirect_to papers_path }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_paper
    @paper = Paper.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def paper_params
    params.require(:paper).permit(:file, :title, :text, :paper_number, :paper_length, :abstract, :keywords, :creation_date, :classification_jel, author_ids: [], priorities: {})
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= form_with(model: paper, local: true) do |form| %>
  <% if paper.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h4>
      <ul>
        <% paper.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div class="create form-group">
      <%= form.label :title %> (required)
      <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
    </div>

    <div class="create form-group">
      <%= form.label :abstract %> (required)
      <%= form.text_area :abstract, :size => "60x12", class: "form-control", placeholder: "Abstract" %>
    </div>

    <div class="create form-group">
      <%= form.label :keywords %> (comma-separated)
      <%= form.text_field :keywords, class: "form-control", placeholder: "Keywords" %>
    </div>

    <div class="create form-group">
      <h3>Authors:
        <span class="small text-muted">
          <%= @paper.authors.map { |author| author.name }.join(', ') %>
        </span>
      </h3>
      <div>(number authors in order, at least one required)</div>
        <div id="authors_boxed_list">
          <ul>
            <% Author.order('lower(name)').all.each do |author| %>
              <% @priorities ? priority = @priorities[author.id] : priority = nil %>
                <span class="three columns alpha">
                  <label>
                    <%= number_field_tag "paper[priorities][#{author.id}]", priority, {min: 1, max: 99} %>
                    <span class="gig-check"><%= author.name %></span>
                  </label>
                </span>
            <% end %>
          </ul>
        </div>
    </div>

    <div id="navigation_button">
      <%= link_to new_author_path, class: "btn btn-outline-secondary" do %>
        <i class="fas fa-user-plus"></i> Create new author
      <% end %>
    </div>

    <div class="create form-group" id="papers_creation_dati">
      <%= form.label :creation_date %> (date paper was written)
      <%= form.text_field :creation_date, class: "form-control", id: "datepicker", placeholder: "Creation date" %>
    </div>

    <div class="create form-group">
      <%= form.label :classification %> (use Journal of Economic Literature codes from this <a href="https://ideas.repec.org/j/" target="_blank">list</a>)
      <%= form.text_field :classification_jel, class: "form-control", placeholder: "Classification" %>
    </div>

    <div class="create form-group">
      <%= form.label :paper_length %> (number of pages if printed)
      <%= form.text_field :paper_length, class: "form-control", placeholder: "Paper length" %>
    </div>

    <div id="file_upload">
      <strong><%= form.label :file_upload %> (required)</strong><br>
      <%= form.file_field :file %>
    </div>

    <div class="actions" id="submit_button">
      <%= form.submit (@paper.new_record? ? "Add Paper" : "Edit Paper"), class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/papers/edit.html.erb
<%= stylesheet_link_tag 'papers', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
  <%= render 'form', paper: @paper %>
</div>

app/views/papers/index.html.erb
<%= stylesheet_link_tag 'papers', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
  <%= form_tag papers_path, { :method => 'get', class: "container", role: "search" } do %>
  <div class="main">
    <div class="input-group">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for papers" %>
      <div class="input-group-append">
        <button class="btn btn-dark" type="submit">
          <i class="fa fa-search"></i>
        </button>
      </div>
    </div>
  </div>
  <% end %>

  <div id="actions">
    <div class="float-left">
      <button type="button" id="check_all" onclick="toggleButton()" class="btn btn-outline-secondary">Select all</button>
    </div>
    <div class="float-right">
      <%= link_to new_paper_path, class: "btn btn-outline-secondary" do %>
        <i class="fas fa-file-alt"></i> <i class="fas fa-plus"></i> Add Paper
      <% end %>
    </div>
  </div>

  <%= form_tag destroy_multiple_papers_path, method: :delete do %>
  <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Are you sure?</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">Would you like to remove these papers from the list?</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
          <%= button_tag type: 'submit', method: :delete, class: "btn btn-danger" do %>
            <i class="fas fa-trash-alt"></i> Delete
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal", id="delete_all_btn">
    <i class="fas fa-trash-alt"></i> Delete all
  </button>

  <div id="table" class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th></th>
          <th scope="col">Title</th>
          <th id="column2" scope="col">Authors</th>
          <th id="column3" scope="col">Added at</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @papers.each do |paper| %>
          <tr>
            <td align="center">
              <%= check_box_tag "papers[]", paper.id %>
            </td>
            <td scope="row"><%= paper.title %>
            </td>
            <td>
              <%= paper.authors.map(&:name).join(", ") %>
            </td>
            <td><%= paper.created_at.in_time_zone('Pacific Time (US & Canada)').strftime('%B %e, %Y %l:%M %p') %></td>
            <td>
              <div class="btn-group float-right">
                <%= link_to paper, class: "btn btn-outline-secondary btn-sm" do %>
                  <i class="fas fa-search"></i> Show
                <% end %>
                <%= link_to edit_paper_path(paper), class: "btn btn-outline-secondary btn-sm" do %>
                  <i class="fas fa-edit"></i> Edit
                <% end %>
                <div class="modal" id="myModal<%= paper.id %>">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title">Are you sure?</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                      </div>
                      <div class="modal-body">Would you like to remove this paper from the list?</div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                        <%= link_to paper, method: :delete, class: "btn btn-danger" do %>
                          <i class="fas fa-trash-alt"></i> Delete
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal<%= paper.id%>">
                  <i class="fas fa-trash-alt"></i> Delete
                </button>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="float-right" id="page_entries_info">
    <%= page_entries_info @papers %>
  </div>
  <% end %>

  <div><%= paginate @papers, window: 2, entry_name: "papers" %></div>
</div>

app/views/papers/new.html.erb
<%= stylesheet_link_tag 'papers', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>

<div class="container">
  <%= render 'form', paper: @paper %>
</div>

app/views/papers/show.html.erb
<%= stylesheet_link_tag 'papers', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
  <table class="table table-bordered" id="show_table">
    <tr>
      <th id="header_names">Title</th>
      <td><%= @paper.title %></td>
    </tr>
    <tr>
      <th id="header_names">Authors</th>
      <td>
        <ul><% @paper.authors.each do |author| %>
          <li><%= author.name %></li>
        <% end %></ul>
      </td>
    </tr>
    <tr>
      <th id="header_names">Abstract</th>
      <td><%= @paper.abstract %></td>
    </tr>
    <tr>
      <th id="header_names">Keywords</th>
      <td><%= @paper.keywords %></td>
    </tr>
    <tr>
      <th id="header_names">Paper Length</th>
      <td><%= @paper.paper_length %></td>
    </tr>
    <tr>
      <th id="header_names">Classification</th>
      <td><%= @paper.classification_jel %></td>
    </tr>
    <tr>
      <th id="header_names">Creation Date</th>
      <td><%= @paper.creation_date&.in_time_zone('Pacific Time (US & Canada)')&.strftime('%B %e, %Y') %></td>
    </tr>
    <tr>
      <th id="header_names">File</th>
      <td><%= link_to 'View file', url_for(@paper.file) %></td>
    </tr>
    <tr>
      <th id="header_names">Published at</th>
      <td><%= @paper.created_at.in_time_zone('Pacific Time (US & Canada)').strftime('%B %e, %Y at %l:%M %p') %></td>
    </tr>
    <tr>
      <th id="header_names">Updated at</th>
      <td><%= @paper.updated_at.in_time_zone('Pacific Time (US & Canada)').strftime('%B %e, %Y at %l:%M %p') %></td>
    </tr>
  </table>

  <div class="float-right" id="navigation_button">
    <%= link_to edit_paper_path(@paper), class: "btn btn-outline-secondary" do %>
      <i class="fas fa-edit"></i> Edit
    <% end %>
    <%= link_to papers_path, class: "btn btn-outline-secondary" do %>
      Back <i class="fas fa-arrow-right"></i>
    <% end %>
  </div>
</div>